In [ ]:
import pandas as pd
import numpy as np
import re

import warnings
warnings.filterwarnings("ignore")

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/jdvelasq/datalabs/master/datasets/amazon_cells_labelled.tsv", header=None, sep='\t',
                 names = ["Sentence", "Feeling"])
df.head()

Sentence  Feeling
0  I try not to adjust the volume setting to avoi...      NaN
1  So there is no way for me to plug it in here i...      0.0
2                        Good case, Excellent value.      1.0
3        I thought Motorola made reliable products!.      NaN
4                         Battery for Motorola Razr.      NaN

In [ ]:
#
# Cargue el archivo usando Pandas e imprima la cantidad de
# registros
#
# Rta/
# 14609
#

len(df)

14609

In [ ]:
#
# Imprima el primer mensaje de texto.
#
# Rta/
# 'I try not to adjust the volume setting to avoid that I turn off the call button which is situated just below the volume adjustment knob.'
#
df['Sentence'][0]

'I try not to adjust the volume setting to avoid that I turn off the call button which is situated just below the volume adjustment knob.'

In [ ]:
#
# Imprima la cantidad de mensajes con NaN
#
# Rta/
# 13609
#
df['Feeling'].isnull().sum()

13609

In [ ]:
#
# Imprima la cantidad de mensajes con valoración igual a 1.0
#
# Rta/
# 500
#
len(df[df['Feeling'] == 1.0])

500

In [ ]:
#
# Imprima la cantidad de mensajes con valoración igual a 0.0
#
# Rta/
# 500
#
len(df[df['Feeling'] == 0.0])

500

In [ ]:
#
# Genere un nuevo dataset que contenga únicamente los registros
# con valoración positiva o negativa e imprima su longitud
#
# Rta/
# 1000
#
dff = df.loc[df['Feeling'].notnull()]
len(dff)

1000

In [ ]:
from nltk.stem.snowball import SnowballStemmer
stemmer = SnowballStemmer("english")
l1 = ["learn", "learned", "learning", "learns", 'work', 'Worked']
for i in l1:
  p = stemmer.stem(i)
  print(p)
print('ok')

learn
learn
learn
learn
work
work
ok


In [ ]:

# dff['Sentence2'] = dff['Sentence'] 

# from nltk.stem.snowball import SnowballStemmer
# stemmer = SnowballStemmer("english")

# # Split the sentences to lists of words.
# dff['Sentence2'] = dff['Sentence2'].str.split()
# dff['Sentence2'] = dff['Sentence2'].apply(lambda x: [stemmer.stem(y) for y in x])
# dff['Sentence2'] = dff['Sentence2'].str.join(' ')

# dff['Sentence2'][1]

In [ ]:
#
# Genere una nueva columna en el nuevo dataset computada como
# el resultado de aplicar el stemmer de Porter al mensaje e
# imprima el primer mensaje transformado
#
# Rta/
# 'so there is no way for me to plug it in here in the us unless i go by a converter.'
#


In [ ]:
from nltk.stem.porter import PorterStemmer
stemmer = PorterStemmer()

In [ ]:
dff["Sentence"] = dff["Sentence"].str.lower()
dff["stemmed"] = dff.Sentence.apply(lambda x: " ".join([stemmer.stem(w) for w in x.split()]))
#dff['stemmed'] = dff['stemmed'].str.replace('\d+', '')
dff.head(10)

Sentence  ...                                            stemmed
1   so there is no way for me to plug it in here i...  ...  so there is no way for me to plug it in here i...
2                         good case, excellent value.  ...                            good case, excel value.
5                              great for the jawbone.  ...                             great for the jawbone.
10  tied to charger for conversations lasting more...  ...  tie to charger for convers last more than 45 m...
11                                  the mic is great.  ...                                  the mic is great.
13  i have to jiggle the plug to get it to line up...  ...  i have to jiggl the plug to get it to line up ...
15  if you have several dozen or several hundred c...  ...  if you have sever dozen or sever hundr contact...
17        if you are razr owner...you must have this!  ...          if you are razr owner...y must have this!
18                needless to say, i wasted my money.  ...                  needless to say, i wast my money.
21                   what a waste of money and time!.  ...                    what a wast of money and time!.

[10 rows x 3 columns]

In [ ]:
dff['stemmed'][1]

'so there is no way for me to plug it in here in the us unless i go by a converter.'

In [ ]:
#
# Construya la matriz de terminos del documento considerando
# las palabras que tengan una frecuencia entre el 0.1% y el 98%,
# y que esten unicamente conformadas por letras.
#
# Imprima el tamaño del vocabulario.
#
# Rta/
# 1554
#

def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'\d+', '', text)
    return text

from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer(
    #preprocessor=preprocess_text,  # elimina los digitos
    analyzer="word",                # a nivel de palabra
    lowercase=True,                 # convierte a minúsculas
    stop_words="english",           # stop_words en inglés
    token_pattern=r"(?u)\b\w\w+\b", # patrones a reconocer
    binary=True,                    # Los valores distintos de cero son fijados en 1
    max_df=0.98,                    # máxima frecuencia a considerar
    min_df=0.001,                   # ignora palabras con baja frecuencia
)
dtm = count_vect.fit_transform(dff.stemmed)
dtm.shape

(1000, 1554)

In [ ]:
#
# Construya la matriz de terminos del documento considerando
# las palabras que tengan una frecuencia entre el 0.1% y el 98%,
# y que esten unicamente conformadas por letras.
#
# Imprima el tamaño del vocabulario.
#
# Rta/
# 1554
#
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer(
    analyzer="word",                # a nivel de palabra
    lowercase=True,                 # convierte a minúsculas
    stop_words="english",           # stop_words en inglés
    token_pattern=r"(?u)\b\w\w+\b", # patrones a reconocer
    binary=True,                    # Los valores distintos de cero son fijados en 1
    max_df=0.98,                    # máxima frecuencia a considerar
    min_df=0.001,                   # ignora palabras con baja frecuencia
)
dtm = count_vect.fit_transform(dff.stemmed)
dtm.shape

(1000, 1554)

In [ ]:
dtm = pd.DataFrame(dtm.toarray(), columns=count_vect.get_feature_names())
dtm

10  100  11  12  13  15  15g  ...  wrongli  ye  year  years  yell  z500a  zero
0     0    0   0   0   0   0    0  ...        0   0     0      0     0      0     0
1     0    0   0   0   0   0    0  ...        0   0     0      0     0      0     0
2     0    0   0   0   0   0    0  ...        0   0     0      0     0      0     0
3     0    0   0   0   0   0    0  ...        0   0     0      0     0      0     0
4     0    0   0   0   0   0    0  ...        0   0     0      0     0      0     0
..   ..  ...  ..  ..  ..  ..  ...  ...      ...  ..   ...    ...   ...    ...   ...
995   0    0   0   0   0   0    0  ...        0   0     0      0     0      0     0
996   0    0   0   0   0   0    0  ...        0   0     0      0     0      0     0
997   0    0   0   0   0   0    0  ...        0   0     0      0     0      0     0
998   0    0   0   0   0   0    0  ...        0   0     0      0     0      0     0
999   0    0   0   0   0   0    0  ...        0   0     0      0     0      0     0

[1000 rows x 1554 columns]

# **Nota: Nos da palabras con letras o menos si le aplico el preprocess para eliminar los numeros da menos de 1500 palabras**


In [ ]:
#
# Construya un clasificador bayesiano que use los primeros
# 500 patrones para entrenamiento y los últimos 500 para
# prueba, e imprima el porcentaje de datos para cada clase
# para la muestra de entrenamiento-
#
# Rta/
# 1.0    52.2
# 0.0    47.8
# Name: label, dtype: float64
#


In [ ]:
lay = dff.loc[:,['Feeling']]
lay

Feeling
1         0.0
2         1.0
5         1.0
10        0.0
11        1.0
...       ...
2901      0.0
2906      0.0
2910      0.0
2911      0.0
2913      0.0

[1000 rows x 1 columns]

In [ ]:
X_train = dtm[0:500]
X_test = dtm[500:]

y_train_true = lay.Feeling[0:500]
y_test_true = lay.Feeling[500:]

In [ ]:
#
# Distribución de los datos en el conjunto de entrenamiento.
#
round(100 * y_train_true.value_counts() / sum(y_train_true.value_counts()), 1)

1.0    52.2
0.0    47.8
Name: Feeling, dtype: float64

In [ ]:
#
# Imprima el porcentaje de datos para cada clase para la muestra
# de prueba, redondeado a un decimal.
#
# Rta/
# 0.0    52.2
# 1.0    47.8
# Name: label, dtype: float64
#
#
# Distribución de los datos en el conjunto de test.
#
round(100 * y_test_true.value_counts() / sum(y_test_true.value_counts()), 1)

0.0    52.2
1.0    47.8
Name: Feeling, dtype: float64

In [ ]:
#
# Cree un clasificador de Bayes y entrenelo. Realice el pronostico
# para la muestra de entrenamiento y compute la matriz de confusion
#
# Rta/
# array([[214,  25],
#        [  1, 260]])
#
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import confusion_matrix

clf = BernoulliNB()
clf.fit(X_train.to_numpy(), y_train_true)

BernoulliNB()

In [ ]:
y_test_pred = clf.predict(X_test.to_numpy())
y_test_pred_prob = clf.predict_proba(X_test.to_numpy())
y_test_pred

array([0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0.,
       1., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1.,
       1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0.,
       0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1.,
       1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0.,
       1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 0., 1.

In [ ]:
# Rta/
# array([[214,  25],
#        [  1, 260]])

In [ ]:
# Matriz de confusion
cm = confusion_matrix(
    y_true=y_test_true,
    y_pred=y_test_pred,
    labels=None,
    normalize=None,
)
cm

array([[153, 108],
       [ 32, 207]])

In [ ]:
#
# Realice el pronostico para los mensajes con valoración 
# indeterminada y compute la cantidad de mensajes positivos
#
# Rta/
# 8284
#

df2 = df.loc[df['Feeling'].isnull()]
len(df2)

13609

In [ ]:
df2["Sentence"] = df2["Sentence"].str.lower()
df2["stemmed"] = df2.Sentence.apply(lambda x: " ".join([stemmer.stem(w) for w in x.split()]))
df2.head(10)

Sentence  ...                                            stemmed
0   i try not to adjust the volume setting to avoi...  ...  i tri not to adjust the volum set to avoid tha...
3         i thought motorola made reliable products!.  ...         i thought motorola made reliabl products!.
4                          battery for motorola razr.  ...                         batteri for motorola razr.
6   when i got this item it was larger than i thou...  ...  when i got thi item it wa larger than i though...
7   (i looked for one that specifically said dcu-6...  ...  (i look for one that specif said dcu-60 and sa...
8   the first time it was turned on the screen dis...  ...  the first time it wa turn on the screen displa...
9   in some programs clicking it is the same as hi...  ...  in some program click it is the same as hit th...
12  what happened was that i only had like 70 cont...  ...  what happen wa that i onli had like 70 contact...
14  i bought five of thes for less than five dollars.  ...   i bought five of the for less than five dollars.
16      i had the two year contract for this service.  ...       i had the two year contract for thi service.

[10 rows x 3 columns]

In [ ]:
dtm2 = count_vect.transform(df2['stemmed'])
dtm2.shape

(13609, 1554)

In [ ]:
dtm2 = pd.DataFrame(dtm2.toarray(), columns=count_vect.get_feature_names())
dtm2

10  100  11  12  13  15  ...  ye  year  years  yell  z500a  zero
0       0    0   0   0   0   0  ...   0     0      0     0      0     0
1       0    0   0   0   0   0  ...   0     0      0     0      0     0
2       0    0   0   0   0   0  ...   0     0      0     0      0     0
3       0    0   0   0   0   0  ...   0     0      0     0      0     0
4       0    0   0   0   0   0  ...   0     0      0     0      0     0
...    ..  ...  ..  ..  ..  ..  ...  ..   ...    ...   ...    ...   ...
13604   0    0   0   0   0   0  ...   0     0      0     0      0     0
13605   0    0   0   0   0   0  ...   0     0      0     0      0     0
13606   0    0   0   0   0   0  ...   0     0      0     0      0     0
13607   0    0   0   0   0   0  ...   0     0      0     0      0     0
13608   0    0   0   0   0   0  ...   0     0      0     0      0     0

[13609 rows x 1554 columns]

In [ ]:
y_val_pred = clf.predict(dtm2.to_numpy())
y_val_pred_prob = clf.predict_proba(dtm2.to_numpy())
y_val_pred

array([0., 1., 1., ..., 1., 1., 0.])

In [ ]:
#
# Realice el pronostico para los mensajes con valoración 
# indeterminada y compute la cantidad de mensajes positivos
#
# Rta/
# 8284
#

unique, counts = np.unique(y_val_pred, return_counts=True)
print(counts[1])

8284
