# 6.2.2 LogisticRegressionCV

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegressionCV

import warnings
warnings.filterwarnings("ignore")

Implementa la regresión logística con validación cruzada para el parámetro C.

In [3]:
X, y = load_breast_cancer(return_X_y=True)

In [4]:
logisticRegressionCV = LogisticRegressionCV(
    # --------------------------------------------------------------------------
    # Each of the values in Cs describes the inverse of regularization strength.
    # If Cs is as an int, then a grid of Cs values are chosen in a logarithmic
    # scale between 1e-4 and 1e4. Like in support vector machines, smaller
    # values specify stronger regularization.
    Cs=[1e-3, 1e-2, 1e-1, 1],
    # --------------------------------------------------------------------------
    # Specifies if a constant (a.k.a. bias or intercept) should be added to the
    # decision function.
    fit_intercept=True,
    # --------------------------------------------------------------------------
    # The default cross-validation generator used is Stratified K-Folds. If an
    # integer is provided, then it is the number of folds used.
    cv=None,
    # --------------------------------------------------------------------------
    # Specify the norm of the penalty:
    # * 'l2': add a L2 penalty term and it is the default choice.
    # * 'l1': add a L1 penalty term.
    # * 'elasticnet': both L1 and L2 penalty terms are added.
    penalty="l2",
    # --------------------------------------------------------------------------
    # A string (see model evaluation documentation) or a scorer callable
    # object / function with signature scorer(estimator, X, y).
    scoring=None,
    # --------------------------------------------------------------------------
    # Algorithm to use in the optimization problem. Default is ‘lbfgs’. To
    # choose a solver, you might want to consider the following aspects:
    # * For small datasets, ‘liblinear’ is a good choice, whereas ‘sag’ and
    #   ‘saga’ are faster for large ones.
    # * For multiclass problems, only ‘newton-cg’, ‘sag’, ‘saga’ and ‘lbfgs’
    #   handle multinomial loss.
    # * ‘liblinear’ and is limited to one-versus-rest schemes.
    # * ‘newton-cholesky’ is a good choice for n_samples >> n_features,
    #   especially with one-hot encoded categorical features with rare
    #   categories. Note that it is limited to binary classification and the
    #   one-versus-rest reduction for multiclass classification. Be aware that
    #   the memory usage of this solver has a quadratic dependency on n_features
    #   because it explicitly computes the Hessian matrix.
    solver="lbfgs",
    # --------------------------------------------------------------------------
    # Tolerance for stopping criteria.
    tol=0.0001,
    # --------------------------------------------------------------------------
    # Maximum number of iterations taken for the solvers to converge.
    max_iter=1000,
    # --------------------------------------------------------------------------
    # Weights associated with classes in the form {class_label: weight}. If not
    # given, all classes are supposed to have weight one.
    # * 'balanced' uses the values of y to automatically adjust weights
    # inversely proportional to class frequencies in the input data as
    # n_samples / (n_classes * np.bincount(y)).
    class_weight=None,
    # --------------------------------------------------------------------------
    # If set to True, the scores are averaged across all folds, and the coefs
    # and the C that corresponds to the best score is taken, and a final refit
    # is done using these parameters.
    #
    # Otherwise the coefs, intercepts and C that correspond to the best scores
    # across folds are averaged.
    refit=True,
    # --------------------------------------------------------------------------
    # Used when solver == ‘sag’, ‘saga’ or ‘liblinear’ to shuffle the data.
    random_state=None,
    # --------------------------------------------------------------------------
    # {‘ovr’, ‘multinomial’, ‘auto’}
    # If the option chosen is ‘ovr’, then a binary problem is fit for each
    # label. For ‘multinomial’ the loss minimised is the multinomial loss fit
    # across the entire probability distribution, even when the data is binary.
    multi_class="auto",
    # --------------------------------------------------------------------------
    # The Elastic-Net mixing parameter, with 0 <= l1_ratio <= 1. Only used if
    # penalty='elasticnet'. Setting l1_ratio=0 is equivalent to using
    # penalty='l2', while setting l1_ratio=1 is equivalent to using penalty='l1'.
    # For 0 < l1_ratio <1, the penalty is a combination of L1 and L2.
    l1_ratios=None,
)

logisticRegressionCV.fit(X, y)

logisticRegressionCV.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,

In [5]:
logisticRegressionCV.intercept_

array([28.31743674])

In [6]:
logisticRegressionCV.coef_

array([[ 1.00772273,  0.18284397, -0.27691529,  0.02276769, -0.1744071 ,
        -0.22270091, -0.52790486, -0.28891103, -0.26172059, -0.03074184,
        -0.07981472,  1.27171883,  0.10702267, -0.10832142, -0.02439403,
         0.06190287, -0.03811407, -0.03726069, -0.03710315,  0.0130745 ,
         0.11818131, -0.43939112, -0.10458489, -0.01349904, -0.3486427 ,
        -0.70110083, -1.41004791, -0.59123028, -0.72390754, -0.09627315]])

In [7]:
logisticRegressionCV.predict_proba(X)[0:10]

array([[1.00000000e+00, 3.24733804e-14],
       [9.99995936e-01, 4.06382637e-06],
       [9.99999453e-01, 5.47165776e-07],
       [6.88315904e-01, 3.11684096e-01],
       [9.99754795e-01, 2.45204605e-04],
       [7.53323104e-01, 2.46676896e-01],
       [9.99994225e-01, 5.77511152e-06],
       [9.89198526e-01, 1.08014740e-02],
       [9.41333360e-01, 5.86666397e-02],
       [9.98536930e-01, 1.46307041e-03]])

In [8]:
logisticRegressionCV.score(X, y)

0.9578207381370826

In [9]:
print('ok_')

ok_
