# 3.2.1 Evaluación de métricas con cross_validate

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

from sklearn import datasets, linear_model
from sklearn.model_selection import cross_validate

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import warnings
warnings.filterwarnings("ignore")

Evalua las métricas indicadas para cada uno de los grupos de test generados cuando se usa un esquema de validación cruzada.

- Permite muliples métricas para evaluación.
- Retorna un diccionario conteniendo los tiempos de entrenamiento y scoring, y el resultado del test.

## 3.2.1.1 Generación de los datos del experimiento

In [3]:
diabetes = datasets.load_diabetes()
X = diabetes.data[:150]
y = diabetes.target[:150]

estimator = linear_model.Lasso()

In [4]:
cv_results = cross_validate(
    # -------------------------------------------------------------------------
    # The object to use to fit the data. Must implement fit()
    estimator=estimator,
    # -------------------------------------------------------------------------
    # The data to fit. Can be for example a list, or an array.
    X=X,
    # -------------------------------------------------------------------------
    # The target variable to try to predict in the case of supervised learning.
    y=y,
    # -------------------------------------------------------------------------
    # Group labels for the samples used while splitting the dataset into
    # train/test set. Only used in conjunction with a “Group” cv instance
    # (e.g., GroupKFold).
    groups=None,
    # -------------------------------------------------------------------------
    # Strategy to evaluate the performance of the cross-validated model on the
    # test set.
    scoring=None,
    # -------------------------------------------------------------------------
    # Determines the cross-validation splitting strategy.
    cv=3,
    # -------------------------------------------------------------------------
    # The verbosity level.
    verbose=0,
    # -------------------------------------------------------------------------
    # Parameters to pass to the fit method of the estimator.
    fit_params=None,
    # -------------------------------------------------------------------------
    # Whether to include train scores.
    return_train_score=False,
    # -------------------------------------------------------------------------
    # Whether to return the estimators fitted on each split.
    return_estimator=False,
    # -------------------------------------------------------------------------
    # Value to assign to the score if an error occurs in estimator fitting.
    error_score=np.nan,
)

sorted(cv_results.keys())

['fit_time', 'score_time', 'test_score']

In [5]:
cv_results["test_score"]

array([0.3315057 , 0.08022103, 0.03531816])

In [6]:
scores = cross_validate(
    estimator,
    X,
    y,
    cv=3,
    scoring=("r2", "neg_mean_squared_error"),
    return_train_score=True,
)

scores["test_neg_mean_squared_error"]

array([-3635.52042005, -3573.35050281, -6114.77901585])

In [7]:
scores["train_r2"]

array([0.28009951, 0.3908844 , 0.22784907])

In [8]:
scores = cross_validate(
    estimator,
    X,
    y,
    cv=3,
    scoring=("r2", "neg_mean_squared_error"),
    return_estimator=True,
)

scores['estimator']

[Lasso(), Lasso(), Lasso()]

In [9]:
print('ok_')

ok_
